### ISSUE TITLE
Image predictions

### ISSUE THREAD

**Issue by sum1lim** [sum1lim/sea_ice_remote_sensing#24]
Write a script that predicts and visualizes the image segmentation using the classification models.

**Comment by omarkawach** [comment]
Process:
- Take an image or images and format correctly into a dataset
- Add GLCM products to each bands
- Normalize using the training dataset 
- Get prediction (load user defined model and feed the image dataset into it)
- Turn 2d array into image 

Need an ML config file to know which classes to merge. 

The classes in the mask should be merged from 15 into 4 before comparing with the prediction.
